[spot]
exchange1 = "binance"
exchange2 = "okx"
symbol = "BTC/USDT"

[futures]
spot_exchange = "binance"
futures_exchange = "okx"
symbol = "BTC/USDT"

[triangle]
exchange = "binance"
pair1 = "BTC/USDT"
pair2 = "ETH/USDT"
pair3 = "ETH/BTC"

[grid]
# 交易参数
trading_asset = "FARTCOIN"    # 交易的币种名称
grid_count = 8                # 网格数量，增加到8个（从5个增加），提高交易频率
trade_amount = 80.0           # 每格交易金额，降低到80（从100降低），分散风险
max_position = 10000.0          # 最大持仓量，防止过度持仓
max_drawdown = 0.02           # 最大回撤限制，当亏损超过2%时触发清仓
price_precision = 4           # 价格精度，保留2位小数
quantity_precision = 1        # 数量精度，保留1位小数
check_interval = 10           # 检查间隔，增加到10秒，减少频繁检查
max_order_age_minutes = 5.0   # 订单最大存活时间5分钟，给订单更多成交机会
order_status_check_interval = 15  # 订单状态检查间隔（秒），默认15秒
leverage = 3                  # 杠杆倍数，使用3倍杠杆
max_active_orders = 20        # 每次最多挂单数量，增加到10个（从6个）
fee_rate = 0.0004              # 手续费率，0.04%
min_profit = 0.002            # 最小盈利阈值，降低到0.002（提高成交概率）
margin_usage_threshold = 0.9  # 保证金使用率阈值，90%

# 网格策略参数
min_grid_spacing = 0.0024    # 最小网格间距，0.25%，平衡利润与成交频率（从0.003降低到0.0025）
max_grid_spacing = 0.004     # 最大网格间距，0.4%，保持合理范围（从0.005降低到0.004）
# min_grid_spacing 和 max_grid_spacing 建议设置为 0.2%~0.3% 以上（即 0.002~0.003），这样每次开平仓的价差能覆盖手续费。
grid_price_offset = 0.0       # 网格价格偏移量，可以设置一个偏移值来调整网格位置

# 风险控制参数
max_single_loss = 0.01        # 单笔最大亏损限制，1%，超过则触发清仓
max_daily_loss = 0.02         # 每日最大亏损限制，2%，超过则停止交易（修复：与最大回撤保持一致）
trailing_stop_ratio = 0.08   # 浮动止损比例，8%（从10%降低），更严格的风险控制
margin_safety_threshold = 1.0  # 保证金安全阈值，100%（修复：提高安全性）
slippage_tolerance = 0.001    # 滑点容忍度，0.1%
max_orders_per_batch = 8      # 每批最大订单数，增加到8个（匹配网格数量）
order_batch_delay_ms = 150    # 批次间延迟毫秒数，减少到150ms（提高执行速度）
max_holding_time = 86400      # 最大持仓时间，86400秒=24小时，超过则强制平仓
history_length = 80           # 价格历史长度，增加到80（更准确的波动率计算）
order_update_threshold = 0.02 # 订单更新阈值，价格变化超过2%时触发订单更新

# 账户配置
[account]
private_key = ""  # 请替换为您的私钥
real_account_address = "0x0C219488E878b66d9e098ED59Ab714c5c29eB0dF"