[spot]
exchange1 = "binance"
exchange2 = "okx"
symbol = "BTC/USDT"

[futures]
spot_exchange = "binance"
futures_exchange = "okx"
symbol = "BTC/USDT"

[triangle]
exchange = "binance"
pair1 = "BTC/USDT"
pair2 = "ETH/USDT"
pair3 = "ETH/BTC"

[grid]
# 交易参数
trading_asset = "FARTCOIN"    # 交易的币种名称
total_capital = 1000.0        # 总资金量，单位USDT
grid_count = 5                # 网格数量，即在价格区间内设置的网格数量（修复：从7减少到5）
trade_amount = 100.0          # 每格交易金额，每次买入或卖出的资金量
max_position = 10000.0          # 最大持仓量，防止过度持仓
max_drawdown = 0.02           # 最大回撤限制，当亏损超过2%时触发清仓
price_precision = 4           # 价格精度，保留2位小数
quantity_precision = 1        # 数量精度，保留1位小数
check_interval = 5            # 检查间隔，每5秒检查一次价格
leverage = 3                  # 杠杆倍数，使用3倍杠杆
max_active_orders = 6           # 每次最多挂单数量（买/卖各自）
fee_rate = 0.0004              # 手续费率，0.04%
min_profit = 0.01              # 最小盈利阈值，单位USDC
margin_usage_threshold = 0.9  # 保证金使用率阈值，90% TODO(目前未使用了)

# 网格策略参数
min_grid_spacing = 0.0018    # 最小网格间距，0.13%，防止网格过密（修复：满足手续费覆盖要求）
max_grid_spacing = 0.002       # 最大网格间距，5%，防止网格过疏
# min_grid_spacing 和 max_grid_spacing 建议设置为 0.2%~0.3% 以上（即 0.002~0.003），这样每次开平仓的价差能覆盖手续费。
grid_price_offset = 0.0       # 网格价格偏移量，可以设置一个偏移值来调整网格位置

# 风险控制参数
max_single_loss = 0.01        # 单笔最大亏损限制，1%，超过则触发清仓
max_daily_loss = 0.02         # 每日最大亏损限制，2%，超过则停止交易（修复：与最大回撤保持一致）
trailing_stop_ratio = 0.1     # 浮动止损比例，10%
margin_safety_threshold = 1.0  # 保证金安全阈值，100%（修复：提高安全性）
slippage_tolerance = 0.001    # 滑点容忍度，0.1%
max_orders_per_batch = 5      # 每批最大订单数，默认5
order_batch_delay_ms = 200    # 批次间延迟毫秒数，默认200ms
max_holding_time = 86400      # 最大持仓时间，86400秒=24小时，超过则强制平仓
history_length = 60           # 价格历史长度，用于计算波动率和调整网格间距

# 账户配置
[account]
private_key = ""  # 请替换为您的私钥
real_account_address = "0x0C219488E878b66d9e098ED59Ab714c5c29eB0dF"